version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - sam build
      - sam deploy
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
