version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "collision-sam-quickstart"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qtvc59iak1s2"
s3_prefix = "collision-sam-quickstart"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
